title: Davide Emilio Quadrellaro
logo:  	CNV00000076.jpg
description: <p> Institut für Diskrete Mathematik & Geometrie, <br>
            FB 1 Algebra, <br>
            Technische Universität Wien, <br>
            Wiedner Hauptstrasse 8-10/104, <br>
            1040 Wien, Austria. </p>

            <p> To send me an email, write first davide[dot]quadrellaro and then put [at]posteo[dot]it </p>    <br>
              
theme: jekyll-theme-minimal
