title: Davide Emilio Quadrellaro
description: Exactum, Room A414
Pietari Kalmin katu 5
Kumpla Campus, University of Helsinki

Email: davide.quadrellaro (at) gmail.com
logo: CNV00000076.jpg
theme: jekyll-theme-minimal
