title: Davide Emilio Quadrellaro
logo:  	CNV00000076.jpg
description: <p>Exactum, Room C427,   <br>  
             
              Pietari Kalmin katu 5, <br>
              
              Kumpula Campus,  <br>
             
              University of Helsinki.</p> <br>
              
             
              <p> davide[dot]quadrellaro[at]gmail[dot]com </p> <br>      
              
              
theme: jekyll-theme-minimal
