title: Davide Emilio Quadrellaro
logo:  	CNV00000076.jpg
description: <p>  Department of Mathematics,   <br>

              University of Torino. <br>
              
              Via Carlo Alberto 10, <br>
              
              10123 Torino, Italy. <br>
             
              </p>               
             
              <p> davide[dot]quadrellaro[at]gmail[dot]com </p>    <br>
              
theme: jekyll-theme-minimal
