title: Davide Emilio Quadrellaro
logo: CNV00000076.jpg
description: Exactum, Room C427, 
              Pietari Kalmin katu 5, Kumpula Campus, 
              University of Helsinki.
theme: jekyll-theme-minimal
