title: Davide Emilio Quadrellaro
logo:  	assets/images/photo:personal.jpg
description: <p>   </p>    <br>
              
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
