title: Davide Emilio Quadrellaro
logo:  	CNV00000076.jpg
description: <p>Exactum, Room C327,   <br>  
             
              Pietari Kalmin katu 5, <br>
              
              Kumpula Campus,  <br>
             
              University of Helsinki.</p>               
             
              <p> davide[dot]quadrellaro[at]gmail[dot]com </p>    <br>   

              --------------------------

              <i> Ihr aber, wenn es soweit sein wird
              Dass der Mensch dem Menschen ein Helfer ist
              Gedenkt unsrer
              Mit Nachsicht. </i> <br>

              Bertold Brecht
              
              
theme: jekyll-theme-minimal
