title: Davide Emilio Quadrellaro
logo: CNV00000076.jpg
description: Exactum, Room C427,   <br>  
             
              Pietari Kalmin katu 5, Kumpula Campus,  <br>
             
              University of Helsinki. <br>
             
             
              davide.quadrellaro[at]gmail.com
theme: jekyll-theme-minimal
