title: Davide Emilio Quadrellaro
logo:  	CNV00000076.jpg
description: <p>  Department of Mathematics “Giuseppe Peano”,   <br>
              
              Via Carlo Alberto 10, 10123 Torino, Italy. <br>
             
              University of Torino.</p>               
             
              <p> davide[dot]quadrellaro[at]gmail[dot]com </p>    <br>
              
theme: jekyll-theme-minimal
