title: Davide Emilio Quadrellaro
logo: foto.jpg
description: <p>Exactum, Room C427,   <br>  
             
              Pietari Kalmin katu 5, <br>
              
              Kumpula Campus,  <br>
             
              University of Helsinki.</p> <br>
             
             
              <p> davide.quadrellaro[at]gmail.com </p> <br>
              
                
theme: jekyll-theme-minimal
