title: Davide Emilio Quadrellaro
logo: CNV00000076.jpg
description: <p>Exactum, Room C427,   <br>  
             
              Pietari Kalmin katu 5, <br>
              
              Kumpula Campus,  <br>
             
              University of Helsinki.</p> <br>
             
             
              davide.quadrellaro[at]gmail.com
theme: jekyll-theme-minimal
